---
- name: Deploy app in new namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
        #kubeconfig: /home/josmbrio/.kube/config
    - name: Deploy nginx app
      k8s:
        src: ./nginx-config.yaml
        state: present
        #kubeconfig: /home/josmbrio/.kube/config
        namespace: my-app