---
- name: Install python3, docker and docker-compose
  hosts: all
  become: yes
  become_user: root
  gather_facts: False
  tasks:
    - name: Make sure python3 and docker are installed
      vars: 
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: 
          - python3
          - docker
        update_cache: yes
        state: present
    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.14.0/docker-compose-linux-{{lookup('pipe','uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Ensure docker is running
      systemd:
        name: docker
        state: started
    - name: Install docker python module
      pip:
        name: 
          - docker
          - docker-compose

- name: Add ec2-user to docker group
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
    - name: Reconnect to server session
      meta: reset_connection

#- name: Test docker pull
#  hosts: docker_server
#  tasks:
#    - name: Pull redis
#      docker_image: 
#        name: redis
#        source: pull

- name: Start docker containers
  hosts: all
#  vars_prompt:
#    - name: docker_password
#      prompt: Enter docker password
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker compose
      copy:
        src: ./docker-compose.yaml
        dest: /home/ec2-user/docker-compose.yaml
    - name: Docker login
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: josmbrio
        password: "{{docker_password}}"
    - name: Start container from compose
      docker_compose:
        project_src: /home/ec2-user
        state: present # docker-compose up