version: '3'
services:
  mysql:
    image: mysql:8.0.30
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pa55w0rd
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=pa55w0rd
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: mysql
      #      command: --default-authentication-plugin=mysql_native_password
  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    ports:
      - 1080:80
    environment:
      - PMA_HOST=mysql
    container_name: phpmyadmin
    depends_on:
      - mysql
volumes:
  mysql-data:
    driver: local