- name: Copy docker compose
  copy:
    src: /home/josmbrio/ansible/docker-compose.yaml
    dest: /home/josmbrio/docker-compose.yaml

- name: Docker login
  docker_login:
    registry_url: "{{docker_registry}}"
    username: "{{docker_username}}"
    password: "{{docker_password}}"

- name: Start container from compose
  docker_compose:
    project_src: /home/josmbrio
    state: present # docker-compose up